// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erpeahzfckyuxxbywgmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVycGVhaHpmY2t5dXh4Ynl3Z21jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODIwMTUsImV4cCI6MjA2Njk1ODAxNX0.cELgbitmfYSht0S8Bk7yq3QEnvQtzO1uccTfZ1LSbrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});